import os
import sys
import uvicorn
import datetime as dt
from typing import Optional, Literal, List
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Ensure project root is in python path
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.execution.broker import SimulatedBroker
from src.core.types import Order, Bar

app = FastAPI(title="Trade Execution Service")

# Global Broker Instance
broker = SimulatedBroker()

# --- Pydantic Models for API ---

class OrderRequest(BaseModel):
    symbol: str
    side: Literal["buy", "sell"]
    type: Literal["market", "limit"]
    qty: float
    price: Optional[float] = None
    tif: str = "GTC"

class BarRequest(BaseModel):
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    ts: Optional[str] = None  # ISO format string

# --- API Endpoints ---

@app.get("/")
def health_check():
    return {"status": "running", "service": "execution-engine"}

@app.post("/orders")
def submit_order(order: OrderRequest):
    """Submit a new order to the broker."""
    try:
        internal_order = Order(
            symbol=order.symbol,
            side=order.side,
            type=order.type,
            qty=order.qty,
            price=order.price,
            tif=order.tif
        )
        order_id = broker.submit(internal_order)
        return {"order_id": order_id, "status": "submitted", "order": order.dict()}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.delete("/orders/{order_id}")
def cancel_order(order_id: str):
    """Cancel an existing order."""
    broker.cancel(order_id)
    return {"status": "cancelled_if_exists", "order_id": order_id}

@app.get("/account")
def get_account():
    """Get current account status (positions, cash, equity)."""
    return broker.account()

@app.post("/market/bar")
def push_market_data(bar_req: BarRequest):
    """
    Simulate market data feed.
    Pushing a bar triggers the matching engine to check for fills.
    """
    # Parse timestamp or use current time
    ts = dt.datetime.now()
    if bar_req.ts:
        try:
            ts = dt.datetime.fromisoformat(bar_req.ts)
        except:
            pass
            
    bar = Bar(
        ts=ts,
        open=bar_req.open,
        high=bar_req.high,
        low=bar_req.low,
        close=bar_req.close,
        volume=bar_req.volume
    )
    
    # Process bar in broker (match orders)
    # The broker returns a list of Fills generated by this bar
    fills = broker.process_bar(bar, bar_req.symbol)
    
    return {
        "processed": True, 
        "symbol": bar_req.symbol,
        "fills_count": len(fills),
        "fills": [
            {
                "order_id": f.order_id,
                "price": f.price,
                "qty": f.qty,
                "fee": f.fee,
                "maker": f.maker,
                "ts": f.ts.isoformat()
            } for f in fills
        ]
    }

def start():
    """Entry point for starting the server programmatically."""
    print("Starting Execution Server on http://0.0.0.0:8001")
    uvicorn.run("src.execution.server:app", host="0.0.0.0", port=8001, reload=True)

if __name__ == "__main__":
    start()